proxies:
  - id: flickr                          # docs @ https://www.flickr.com/services/feeds/docs/photos_public/
    uri: https://api.flickr.com
    methods:
      - GET
  - id: flickrUnsecure
    uri: https://api.flickr.com
    skipHostnameVerification: true
    methods:
      - GET
