proxies:
  - id: flickr                          # docs @ https://www.flickr.com/services/feeds/docs/photos_public/
    uri: https://api.flickr.com
    methods:
      - GET
  - id: flickr-unsecure
    uri: https://api.flickr.com
    skipHostnameVerification: true
    methods:
      - GET
  - id: spinnaker
    uri: https://api.spinnaker:7103
    keyStore: /path/to/my/keystore.jks
    keyStorePasswordFile: /path/to/my/password.txt
  - id: spinnaker-invalid
    uri: https://api.spinnaker:7103
